version: '3.9'
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/16

volumes:
  pgdata:


services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/pstgresql/data/
    ports:
      - "5432:5432"
    networks:
      - postgres    
  
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: "test1234"
      POSTGRES_DB: "TestDB"
      POSTGRES_USER: "testUser"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - postgres
    volumes:
      - ./private/var/lib/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "test1234"
  